# Config file for project

# PyTorch model hyperparameters
MODEL:
  HIDDEN_SIZE: None
  NUM_LAYERS: None
  LEARNING_RATE: None
  BATCH_SIZE: None

# PyTorch Lightning hyperparameters
LIGHTNING:
  MAX_EPOCHS: None
  EARLY_STOPPING_PATIENCE: None
  TRAIN_PERCENT_CHECK: None
